### ISSUE TITLE
Update to 3.1.0 bug on Extension UECS

### ISSUE THREAD

**Issue by InfiBatnis** [sebas77/Svelto.ECS#58]
When Update from 3.0.3 to 3.1.0 get error, cannot detect assembly form  DOT\Job

Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Extensions\Unity\DOTS\UECS\IUECSSubmissionEngine.cs(8,58): error CS0246: The type or namespace name 'IJobifiedEngine' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Extensions\Unity\DOTS\UECS\SveltoOverUECSEnginesGroup.cs(26,46): error CS0246: The type or namespace name 'IJobifiedEngine' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Extensions\Unity\DOTS\UECS\SyncSveltoToUECSGroup.cs(7,42): error CS0246: The type or namespace name 'JobifiedEnginesGroup<>' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Extensions\Unity\DOTS\UECS\SyncSveltoToUECSGroup.cs(11,64): error CS0246: The type or namespace name 'IJobifiedEngine' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Extensions\Unity\DOTS\UECS\SyncUECSToSveltoGroup.cs(7,42): error CS0246: The type or namespace name 'JobifiedEnginesGroup<>' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Extensions\Unity\DOTS\UECS\SyncUECSToSveltoGroup.cs(12,64): error CS0246: The type or namespace name 'IJobifiedEngine' could not be found (are you missing a using directive or an assembly reference?)

**Comment by sebas77** [comment]
thank you! can you send me your manifest.json please

**Comment by InfiBatnis** [comment]
[manifest.zip](https://github.com/sebas77/Svelto.ECS/files/5796448/manifest.zip)

**Comment by InfiBatnis** [comment]
I  just downgrade to 3.0.3

**Comment by sebas77** [comment]
of course, but it's important you keep on reporting these bugs. They will be fixed 👍

**Comment by sebas77** [comment]
what version of unity are you using?

**Comment by sebas77** [comment]
OK I reproed it

**Comment by sebas77** [comment]
3.1.1 is out, please check if it is fixed
