### ISSUE TITLE
error CS0246: The type or namespace name 'ConditionalAttribute' could not be found

### ISSUE THREAD

**Issue by zinkins** [sebas77/Svelto.ECS#59]
After updating SECS and Common from 3.0.2 to 3.1.0 I got these error messages
_Library\PackageCache\com.sebaslab.svelto.ecs@3.1.0\Core\CheckEntityUtilities.cs(17,10): error CS0246: The type or namespace name 'ConditionalAttribute' could not be found (are you missing a using directive or an assembly reference?)_
I added _using System.Diagnostics;_ into the CheckEntityUtilities class and it works now

**Comment by sebas77** [comment]
fixed in 3.1.1
